@baseUrl = http://localhost:5000/api
@token = empty_token

#@baseUrl = http://localhost:5000/api

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "admin@test.com",
    "password": "Test12345!",
    "tenantCode": "demo001"
}

### Update user status
PATCH {{baseUrl}}/users/67486e71ef7c986d25327d7c/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDg0NTdhZWY3Yzk4NmQyNTMyN2NlMyIsInVzZXJuYW1lIjoidGVzdGFkbWluIiwicm9sZSI6ImFkbWluIiwidGVuYW50SWQiOiI2NzQ3ZWUzYzk2NzNlZDUxZGMxN2UyOWUiLCJpYXQiOjE3MzI4MDEzNDAsImV4cCI6MTczMjgzMDE0MH0.iZwoknJcWCVGVtBHvcmMvgTaGBgrV5e9t568-DXLtwE
Content-Type: application/json

{
    "status": "inactive"
}

### Update password
PUT {{baseUrl}}/users/67486e71ef7c986d25327d7c/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NDg0NTdhZWY3Yzk4NmQyNTMyN2NlMyIsInVzZXJuYW1lIjoidGVzdGFkbWluIiwicm9sZSI6ImFkbWluIiwidGVuYW50SWQiOiI2NzQ3ZWUzYzk2NzNlZDUxZGMxN2UyOWUiLCJpYXQiOjE3MzI4MDEzNDAsImV4cCI6MTczMjgzMDE0MH0.iZwoknJcWCVGVtBHvcmMvgTaGBgrV5e9t568-DXLtwE
Content-Type: application/json

{
    "currentPassword": "Staff@123",
    "newPassword": "Staff@1234"
}
